version: '3'
services:
  nextjs-app:
    image: node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3005:3000"
    env_file:
      - .env
    command: bash -c "npm i && npm run build && npm run start"
    networks:
      - common_net
  
networks:
  common_net: {}